export {
  initDatabase,
  closeDatabase,
  savePosition,
  loadActivePositions,
  loadAllPositions,
  saveLaunchedToken,
  loadLaunchedTokens,
  savePerformanceResult,
  loadPerformanceResults,
  saveCategoryPerformance,
  loadCategoryPerformance,
  saveFactorCorrelation,
  loadFactorCorrelations,
  saveWeights,
  loadWeights,
  saveMeta,
  loadMeta,
  saveGasRecord,
  loadGasRecords,
  type PositionRow,
  type LaunchedTokenRow,
  type PerformanceResultRow,
  type CategoryPerformanceRow,
  type ScoringWeightsRow,
  type GasRecordRow,
} from "./database.js";

export {
  hydrateFromDatabase,
  persistPosition,
  persistLaunchResult,
  persistPerformanceResult,
  persistCategoryPerformance,
  persistFactorCorrelations,
  persistWeights,
  persistMeta,
  persistGasRecord,
  type HydrationTarget,
  type HydrationResult,
} from "./state-sync.js";
